- name: swe_agent

  _target_: uni_agent.agent_loop.UniAgentLoop

  concurrency: 32
  log_dir: /tmp/swebench_llm_router
  mask_abnormal_exit_traj: false

  interaction:
    action_timeout: 300
    max_turns: 100

  env:
    deployment:
      type: local
      startup_timeout: 1200
      container_runtime: docker
    env_variables:
      PIP_PROGRESS_BAR: "off"
      PIP_CACHE_DIR: "~/.cache/pip"
      PAGER: "cat"
      MANPAGER: "cat"
      LESS: "-R"
      TQDM_DISABLE: "1"
      GIT_PAGER: "cat"

  tool_parser: hermes

  tools:
    - name: str_replace_editor
    - name: execute_bash
    - name: submit

  reward:
    eval_timeout: 600
